version: "2"

sql:
  - schema: "../internal/constants/query/schemas"
    queries: "../internal/constants/query/queries"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "../internal/constants/model/db"
        sql_package: "pgx/v5"
        emit_json_tags: true
        overrides:
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
            nullable: false
          - db_type: "uuid"
            go_type: "github.com/google/uuid.NullUUID"
            nullable: true
          - db_type: "timestamptz"
            go_type: "time.Time"
            nullable: false
          - db_type: "pg_catalog.float8"
            go_type: "database/sql.NullFloat64"
            nullable: true
          - db_type: "pg_catalog.int8"
            go_type: "database/sql.NullInt64"
            nullable: true
          - db_type: "text"
            go_type: "database/sql.NullString"
            nullable: true
